### ISSUE TITLE
Don't mix double quote with single quote in code

### ISSUE THREAD

**Issue by thunderace** [digistump/OakCLI#9]
With nodeJS don't use double quote (") for text, only single quote.
I have a pull request ready but, my oak seem to be dead and i cannot test for now (i will reset oak when i will back to home).
Other changes : 
- Error messages in red,
- check the particle cloud order (error if offline or inline messages are detected before the flashing succes message),
- double quotes remplaced by simple quotes,
- code reformatting.

Remark : keep the content test for 'spark/flash/status' message because you can have a failed here, not always success (i saw this message only once in the particle dashboard).

**Comment by digistump** [comment]
This sounds like some good changes - thanks - one note though - I commented out the interpretation of the  "'spark/flash/status' message" because there is a known issue on the Particle side of things where this gives false errors quite frequently - meaning even if this status message says it failed it very likely may have succeeded. Particle is supposed to fix this fairly soon (it affects all of their boards too) - but until they do we can't rely on that.

**Comment by thunderace** [comment]
I saw that there is an issue with the 'spark/flash/status' but never seen it. I'm agree to disable this for now.
I'm working on an enhanced version with one optional parameter. It looks like this :  
`node /home/thunder/repo.git/OakCLI/oak.js -d oak1 ./build.oak/start.bin`
with the optional d parameter the binary file will be upload to the oak1 device, Usefull when you have more than one oak and using OakCLI with the command line or makefile like this one : [Oak-Arduino-Makefile](https://github.com/thunderace/Oak-Arduino-Makefile)

After my tests with OakCore 0.9.4 and 0.9.5, my two oaks are gone, no more wifi connection, i think i will have to use my serial adaptor to bring them back to life...

**Comment by thunderace** [comment]
I close this, the pull request is ready
